version: '3'

services:
#####################################
#   Setup react js container        #
#####################################
  web:
    build: ./sys-stats
    expose:
      - 3000
    ports:  # expose 3000 on host and sent to 3000 in container
      - 3000:3000
######################################
#   Setup nginx                      #
######################################
  nginx:
    image: nginx:alpine
    ports:
      - '80:80' # expose 80 on host and sent to 80 in container
    depends_on: 
      - web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro


#######################################
#   Setup Python Backend Application  #
#######################################

  backend:
    build: ./api
    container_name: backend
    expose:
      - '5000'
    ports:   # expose 5000 on host and sent to 5000 in container
      - 5000:5000




