FROM python:latest

# set the working directory in the container
WORKDIR /app

# copy the dependencies file to the working directory
ADD . /app

# install dependencies
RUN pip3 install -r requirements.txt

# command to run on container start
CMD ["gunicorn", "-b", "0.0.0.0:5000","wsgi:app" ]
